// sgip 协议相关 const

package sgip

// Command ID
const (
	SGIP_BIND = 0x00000001 + iota
	SGIP_UNBIND
	SGIP_SUBMIT
	SGIP_DELIVER
	SGIP_REPORT
	SGIP_ADDSP
	SGIP_MODIFYSP
	SGIP_DELETESP
	SGIP_QUERYROUTE
	SGIP_ADDTELESEG
	SGIP_MODIFYTELESEG
	SGIP_DELETETELESEG
	SGIP_ADDSMG
	SGIP_MODIFYSMG
	SGIP_DELETESMG
	SGIP_CHECKUSER
	SGIP_USERRPT
)

const (
	SGIP_BIND_REP = 0x80000001 + iota
	SGIP_UNBIND_REP
	SGIP_SUBMIT_REP
	SGIP_DELIVER_REP
	SGIP_REPORT_REP
	SGIP_ADDSP_REP
	SGIP_MODIFYSP_REP
	SGIP_DELETESP_REP
	SGIP_QUERYROUTE_REP
	SGIP_ADDTELESEG_REP
	SGIP_MODIFYTELESEG_REP
	SGIP_DELETETELESEG_REP
	SGIP_ADDSMG_REP
	SGIP_MODIFYSMG_REP
	SGIP_DELETESMG_REP
	SGIP_CHECKUSER_REP
	SGIP_USERRPT_REP
)

// 返回状态码
const (
	SUCC = iota
)

// MessageCoding
const (
	ASCII = 0  // 纯ASCII字符串
	UCS2  = 8  // UCS2编码
	GBK   = 15 // GBK编码
)

// package len
const (
	SGIP_HEAD_LEN   = 20
	SGIP_REP_LEN    = SGIP_HEAD_LEN + 9
	SGIP_BIND_LEN   = SGIP_HEAD_LEN + 41
	SGIP_REPORT_LEN = SGIP_HEAD_LEN + 44
)
